language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script: composer install

script: vendor/bin/phpunit

after_script: vendor/bin/coveralls

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
